import AwsSdk = require("aws-sdk");
import { CliArguments, CliAction } from "./arg-parsing";
import { buildBundle } from "../bundle";
import { AwsCredentials, lambdaDeployer, roleCreator, lambdaScheduler } from "../aws/aws";

const DEFAULT_ROLE_NAME = "autogenerated-dev-bot-role";

export async function deploy(rootDirectory: string, // Absolute path to project
                             entryPoint: string, // Relative path in project to entrypoint
                             functionName: string,
                             region: string,
                             awsCredentials: AwsCredentials,
                             roleName: string = null,
                             env: { [id: string]: string } = {}): Promise<void> {
    let bundle = await buildBundle({ rootDirectory, entryPoint, env });

    let role = await roleCreator.createRole(roleName || DEFAULT_ROLE_NAME, awsCredentials);

    let lambdaArn = await lambdaDeployer.deployLambdaBundle(bundle, {
        functionName,
        region,
        handler: "dev-bot-handler.handler",
        role
    }, awsCredentials);

    await lambdaScheduler.scheduleLambda(lambdaArn, region, awsCredentials);
}
